version: '3.9'
services:
  larapine:
    image: larapine
    container_name: larapine
    build:
      context: ./runtimes/81
      dockerfile: Dockerfile
    volumes:
      - ./src/:/var/www/html/:rw
    ports:
      - 8000:80
      - 5173:5173
      - 6001:6001
    networks:
      - larapine-network

  mysql:
    image: 'mysql/mysql-server:8.0'
    container_name: larapine-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'larapine'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'larapine'
      MYSQL_USER: 'larapine'
      MYSQL_PASSWORD: 'larapine'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    restart: always
    volumes:
      - 'larapine-mysql:/var/lib/mysql'
    ports:
      - 3307:3306
    networks:
      - larapine-network
  
  postgres:
    image: postgres:15.3-alpine3.17
    container_name: larapine-postgres
    environment:
      POSTGRES_PASSWORD: larapine
      POSTGRES_USER: larapine
      POSTGRES_DB: larapine
    restart: always
    volumes:
      - 'larapine-postgres:/var/lib/postgresql/data'
    ports:
      - 5433:5432
    networks:
      - larapine-network

  mailpit:
    image: 'axllent/mailpit:latest'
    container_name: larapine-mailpit
    ports:
      - '${FORWARD_MAILPIT_PORT:-1025}:1025'
      - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
    networks:
      - larapine-network

volumes:
  larapine-mysql:
    driver: local
  larapine-postgres:
    driver: local

networks:
  larapine-network:
    name: larapine-network
    external: true
