version: '3.9'
services:
  larapine:
    image: larapine
    container_name: larapine
    build:
      context: ./runtimes/81
      dockerfile: Dockerfile
    volumes:
      - ./src/:/var/www/html/:rw
    ports:
      - 8000:80
    networks:
      - larapine-network

  mysql:
        image: 'mysql/mysql-server:8.0'
        container_name: larapine-mysql
        environment:
            MYSQL_ROOT_PASSWORD: 'larapine'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: 'larapine_test'
            MYSQL_USER: 'larapine'
            MYSQL_PASSWORD: 'larapine'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'larapine-mysql:/var/lib/mysql'
        networks:
            - larapine-network

  mailpit:
        image: 'axllent/mailpit:latest'
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        networks:
            - larapine-network

volumes:
    larapine-mysql:
        driver: local

networks:
  larapine-network:
    name: larapine-network
    external: true
